theme: minima
title: First Official GitHub Page
author: meetShevene
email: hi@meetshevene.com
description: > # this means to ignore newlines until "baseurl:"
 This is a wonderful site, well not really but, do not worry about it all you need to know is I tried.

# social links
twitter_username: twitter.com/meetshevene # DO NOT include the @ character, or else the build will fail!
github_username:  github.com/meetshevene # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
